### ISSUE TITLE
RFE: create a wiki page documenting the commit message format

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-documentation#18]
The quick answer here is to simply use the Linux Kernel format, but we need something more explicit as non-kernel developers and non-git users, such as Steve are having a hard time understanding git commits.

**Comment by pcmoore** [comment]
Wiki page: https://github.com/linux-audit/audit-documentation/wiki/SPEC-Repository-Commit-Fomat

The page should be sufficient at this point, but we really should select a license for the documentation before we can consider this issue closed.

**Comment by rgbriggs** [comment]
This is the licence I think is most appropriate for this body of work: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by pcmoore** [comment]
@stevegrubb see Richard's comment above regarding CC BY-SA 4.0.

**Comment by rgbriggs** [comment]
Given we discussed dropping the SA clause to not force other users to open proprietary distributions, let's recommend instead CC BY 4.0  https://creativecommons.org/licenses/by/4.0/

**Comment by pcmoore** [comment]
To add some more clarity to Richard's comment above, @stevegrubb explicitly agreed to using the CC BY 4.0 license at a meeting earlier today.  I'm going to update our documentation with this information and close out this issue.

Thanks guys.

**Comment by pcmoore** [comment]
I've added a footer to the wiki indicating that the wiki contents are licensed under CC BY 4.0 and I added a LICENSE file to the repository itself with the CC BY 4.0 license.  I'm considering this closed.
