### ISSUE TITLE
RFE: add a CSV database for audit message types

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-documentation#21]
Create a master documentation audit message type dictionary similar to the existing [audit field dictionary](https://github.com/linux-audit/audit-documentation/blob/master/specs/fields/field-dictionary.csv)

Start with `audit.h`, `libaudit.h` and `ausearch -m 2>&1 | tr ' ' '\n'| grep "^[A-Z]" | tail -n +4 | sort | less`

**Comment by pcmoore** [comment]
At the very least I think the record db should contain the record name, numerical value, and a short description of the record.  We can, and should, add additional information at some point, but even just the above basics would be helpful and worthwhile.

**Comment by rgbriggs** [comment]
Pushed https://github.com/linux-audit/audit-documentation/blob/master/specs/messages/message-dictionary.csv

**Comment by pcmoore** [comment]
_Administrivia: normalized the subject_

**Comment by pcmoore** [comment]
@rgbriggs It is "SELinux" not "SE Linux", please correct this.

**Comment by rgbriggs** [comment]
@pcmoore Yup, that was a preliminary baseline commit.  I've got a pile of corrections/elaborations already along with correct speeeling of IPsec...  Notice I haven't closed it yet...

**Comment by pcmoore** [comment]
@rgbriggs we've talked about this in the past, but I'll mention it again: do not push commits that have known problems, _especially_ when those problems are trivial to fix.  Please address these problems ASAP and refrain from pushes like this in the future.

**Comment by rgbriggs** [comment]
Adding a column to indicate it is a syscall auxiliary record would also be useful, I think.

**Comment by rgbriggs** [comment]
Add origin and class columns: https://github.com/linux-audit/audit-documentation/commit/daae7caf7250d0798db062eb847c809a8bb05aef
