### ISSUE TITLE
Q: how to audit Docker logs

### ISSUE THREAD

**Issue by KSGJ-CLOUD** [linux-audit/audit-documentation#32]
I installed auditd in Docker, but it couldn't start up

**Comment by pcmoore** [comment]
At present time the audit daemon can only be run in the host system's namespace, it cannot be run from inside a container.

**Comment by KSGJ-CLOUD** [comment]
> At present time the audit daemon can only be run in the host system's namespace, it cannot be run from inside a container.

Do you have any reference steps on how to run audit in the host namespace？

**Comment by rgbriggs** [comment]
On 2024-03-20 19:01, KSGJ-CLOUD wrote:
> > At present time the audit daemon can only be run in the host system's namespace, it cannot be run from inside a container.
> 
> Do you have any reference steps on how to run audit in the host namespace？

Don't let it spawn a user or pid namespace.  Those are the two that matter to audit.
